theme: jekyll-theme-minimal
title: Xiaoyu Zhai
locale: en_US
logo: images/megaman.gif
owner:
  name: Xiaoyu Zhai
  bio: "🔭 Working on DL/ML frameworks and MLSys"
  linkedin: xiaoyuzhai
  github: ryantd